from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication, QWidget,  QPushButton, QHBoxLayout, QVBoxLayout, QLabel, QMessageBox, QRadioButton
app=QApplication([])
main_win=QWidget()
main_win.resize(400,200)
main_win.setWindowTitle("Конкурс від Crazy People")

question=QLabel("Як звали першого ютуб-блогера, який набрав 100000000 підписників?")
btn1=QRadioButton("PewDiePie")
btn2=QRadioButton("Рет і Лінк")
btn3=QRadioButton("SlivkiShow")
btn4=QRadioButton("TheBrianMaps")
btn5=QRadioButton("Mister Max")
btn6=QRadioButton("EeOneGuy")

layout_main=QVBoxLayout()
layoutH1=QHBoxLayout()
layoutH2=QHBoxLayout()
layoutH3=QHBoxLayout()
layoutH4=QHBoxLayout()

layoutH1.addWidget(question,alignment=Qt.AlignCenter)
layoutH2.addWidget(btn1,alignment=Qt.AlignCenter)
layoutH2.addWidget(btn2,alignment=Qt.AlignCenter)
layoutH3.addWidget(btn3,alignment=Qt.AlignCenter)
layoutH3.addWidget(btn4,alignment=Qt.AlignCenter)
layoutH4.addWidget(btn5,alignment=Qt.AlignCenter)
layoutH4.addWidget(btn6,alignment=Qt.AlignCenter)
layout_main.addLayout(layoutH1)
layout_main.addLayout(layoutH2)
layout_main.addLayout(layoutH3)
layout_main.addLayout(layoutH4)
main_win.setLayout(layout_main)
def show_win():
    victory=QMessageBox()
    victory.setText("Правильно! Ви виграли зустріч з творцями каналу!")
    victory.exec_()
def show_lose():
    lose=QMessageBox()
    lose.setText("Пощастить іншим разом!")
    lose.exec_()

btn1.clicked.connect(show_win)
btn2.clicked.connect(show_lose)
btn3.clicked.connect(show_lose)
btn4.clicked.connect(show_lose)
btn5.clicked.connect(show_lose)
btn6.clicked.connect(show_lose)
main_win.show()
app.exec_()